/**
 Sumo Architecture List
 Add content to the following sections in this sidebar Navigation file:

  Manage: Admin level options, collection, connections, etc
  Dashboards & Visuals: New and Classic Dashboards, Library of Dashboards, Alerts, Monitors, Alerts, Monitors, SLOs, Health Events, Connections 
  Searches & Logs: Log Search, All Log Searches, Livetail, Lookup, Log Config
  Metrics & Logs: Metrics Search, All Metrics Searches, Config
  Infrastructure Monitoring: Kubernetes, AWS Observability, Root Cause Explorer,
  APM: Application Monitoring (Applications, Services, Service Map, Transaction traces, Span analytics, Root Cause Explorer), RUM
  Incidents Management: Incidents, Triage, Entities, Playbooks
  Security Events: Security Evenets, Insights, Signals, Entities, Records
  Security Detection: Rules, Rules Tuning, Threat Intelligence, Match List, File Analysis, Custom Insights, Network Blocks, Suppressed Entites, Suppressed Lists
 */

module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Get Started',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'get-started/index'},
      items: [
        'get-started/sign-up',
        'get-started/system-requirements',
        'get-started/manage-account',
        {
          type: 'category',
          label: 'Checklists',
          collapsible: true,
          collapsed: true,
          items: [
            'get-started/checklist',
            'get-started/checklist-analyst',
            'get-started/checklist-admins',
          ]
        },
        'get-started/get-help',
        'get-started/keyboard-shortcuts',
        {
          type: 'category',
          label: 'FAQs',
          collapsible: true,
          collapsed: true,
          items: [
            'get-started/sumo-faqs',
            'get-started/certification-faqs',
          ]
        },
        'get-started/sumo-logic-components',
        'get-started/sumo-logic-ui',
        {
          type: 'category',
          label: 'Library',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'get-started/library/index'},
          items: [
            'get-started/library/manage-library',
            'get-started/library/search-the-library',
          ]
        },
        {
          type: 'category',
          label: 'Sumo Logic Apps',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'get-started/library/sumo-logic-apps'},
          items: [
            'get-started/library/install-apps',
            'get-started/library/run-searches-from-apps',
            'get-started/library/log-analysis-quickstart-app'
          ]
        },
      ],
    },
    {
// *** QUICKSTARTS & TUTORIALS 
      type: 'category',
      label: 'Quickstarts and Tutorials',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'quickstart/index'},
      items: [
        'quickstart/quickstart-aws',
        'quickstart/quickstart-github',
        'quickstart/quickstart-k8s',
      ],
    },
    {
      //Put in stuff to test, will be moved later!
      type: 'category',
      label: 'Converted Docs',
      collapsible: true,
      collapsed: true,
      items: [
        'CSE/global-intel'
      ],
     },
  ],
// ***   MANAGE CONTENT: Admin level options, collection, connections, etc
  manage: [
    'manage/manage',
    {
      type: 'category',
      label: 'Collection',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'manage/collection/index'},
      items: [
        'manage/collection/search-for-a-collector-or-source',
        'manage/collection/start-stop-collector-using-scripts',
        'manage/collection/edit-collector',
        'manage/collection/restart-collectors',
        'manage/collection/edit-source',
        'manage/collection/pause-and-resume-source',
        'manage/collection/delete-collector-or-source',
        'manage/collection/set-collector-cpu-usage-target',
        'manage/collection/upgrade-collectors',
        'manage/collection/collector-logs',
        {
          type: 'category',
          label: 'Processing Rules',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'manage/collection/processing-rules/index'},
          items: [
            'manage/collection/processing-rules/create-a-processing-rule',
            'manage/collection/processing-rules/data-forwarding-rules',
            'manage/collection/processing-rules/hash-rules',
            'manage/collection/processing-rules/include-and-exclude-rules',
            'manage/collection/processing-rules/metrics-include-and-exclude-rules',
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Connections and Integrations',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'manage/connections-and-integrations/index'},
      items: [
        {
          type: 'category',
          label: 'Webhook Connections',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'manage/connections-and-integrations/webhook-connections/index'},
          items: [
            'manage/connections-and-integrations/webhook-connections/schedule-searches-for-webhook-connections',
            'manage/connections-and-integrations/webhook-connections/set-up-webhook-connections',
            'manage/connections-and-integrations/webhook-connections/use-the-audit-index-with-webhook-connections',
            'manage/connections-and-integrations/webhook-connections/aws-lambda',
            'manage/connections-and-integrations/webhook-connections/cloud-soar',
            'manage/connections-and-integrations/webhook-connections/datadog',
            'manage/connections-and-integrations/webhook-connections/hipchat',
            'manage/connections-and-integrations/webhook-connections/microsoft-azure-functions',
            'manage/connections-and-integrations/webhook-connections/microsoft-teams',
            'manage/connections-and-integrations/webhook-connections/new-relic',
            'manage/connections-and-integrations/webhook-connections/opsgenie-legacy',
            'manage/connections-and-integrations/webhook-connections/opsgenie',
            'manage/connections-and-integrations/webhook-connections/pagerduty',
            'manage/connections-and-integrations/webhook-connections/slack',
            {
              type: 'category',
              label: 'Jira',
              collapsible: true,
              collapsed: true,
              link: {type: 'doc', id: 'manage/connections-and-integrations/webhook-connections/jira/index'},
              items: [
                'manage/connections-and-integrations/webhook-connections/jira/jira-cloud',
                'manage/connections-and-integrations/webhook-connections/jira/jira-server',
                'manage/connections-and-integrations/webhook-connections/jira/jira-service-desk',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'ServiceNow',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'manage/connections-and-integrations/servicenow/index'},
          items: [
            'manage/connections-and-integrations/servicenow/launch-investigations',
            'manage/connections-and-integrations/servicenow/set-up-searches-for-servicenow-integration',
            'manage/connections-and-integrations/servicenow/set-up-servicenow-connections',
            'manage/connections-and-integrations/servicenow/set-up-a-servicenow-incident-webhook-connection',
          ],
        },
        'manage/connections-and-integrations/sumo-logic-add-on-for-heroku',
        'manage/connections-and-integrations/jfrog-artifactory-sumo-logic-integration',
      ],
    },
    {
      type: 'category',
      label: 'Content Sharing',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'manage/content-sharing/index'},
      items: [
        'manage/content-sharing/admin-mode',
        'manage/content-sharing/changing-alerts',
        'manage/content-sharing/content-sharing-faq',
        'manage/content-sharing/share-content',
      ]
    },
    {
      type: 'category',
      label: 'Data Forwarding',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'manage/data-forwarding/index'},
      items: [
        'manage/data-forwarding/data-forwarding-installed-collectors',
        'manage/data-forwarding/data-forwarding-to-s3',
        'manage/data-forwarding/data-forwarding-amazon-s3-bucket',
        'manage/data-forwarding/manage-data-forwarding',
      ]
    },
    {
      type: 'category',
      label: 'Field Extractions',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'manage/field-extractions/index'},
      items: [
        'manage/field-extractions/field-naming-convention',
        'manage/field-extractions/create-a-field-extraction-rule',
        'manage/field-extractions/edit-field-extraction-rules',
        'manage/field-extractions/example-template',
        {
          type: 'category',
          label: 'Field Extractions',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'manage/field-extractions/fer-templates/index'},
          items: [
            'manage/field-extractions/fer-templates/akamai-cloud-monitor',
            'manage/field-extractions/fer-templates/apache-access-logs',
            'manage/field-extractions/fer-templates/apache-tomcat-access-logs',
            'manage/field-extractions/fer-templates/aws-cloudtrail-logs',
            'manage/field-extractions/fer-templates/aws-elastic-load-balancing-logs',
            'manage/field-extractions/fer-templates/aws-s3-usage-logs',
            'manage/field-extractions/fer-templates/cisco-app',
            'manage/field-extractions/fer-templates/microsoft-iis-logs',
            'manage/field-extractions/fer-templates/nginx-logs',
            'manage/field-extractions/fer-templates/palo-alto-networks',
            'manage/field-extractions/fer-templates/varnish-logs',
          ]
        },
        'manage/field-extractions/parse-elb-logs',
        'manage/field-extractions/apache-tomcat-access-log-fer',
        'manage/field-extractions/cisco-fwsm-fer',
        'manage/field-extractions/safend-field-extraction',
      ]
    },
    {
      type: 'category',
      label: 'Ingestion and Volume',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'manage/ingestion-and-volume/index'},
      items: [
        'manage/ingestion-and-volume/log-ingestion',
        'manage/ingestion-and-volume/collection-status-page',
        {
          type: 'category',
          label: 'Data Volume Index',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'manage/ingestion-and-volume/data-volume-index/index'},
          items: [
            'manage/ingestion-and-volume/data-volume-index/log-tracing-data-volume-index',
            'manage/ingestion-and-volume/data-volume-index/metrics-data-volume-index',
          ]
        },
        {
          type: 'category',
          label: 'Ingest Budgets',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'manage/ingestion-and-volume/ingest-budgets/index'},
          items: [
            'manage/ingestion-and-volume/ingest-budgets/assign-collector-ingest-budget',
            'manage/ingestion-and-volume/ingest-budgets/ingest-budgets-quick-start-tutorial',
          ]
        },
        'manage/ingestion-and-volume/monitor-ingestion-receive-alerts',
      ]
    },
    {
      type: 'category',
      label: 'Manage Subscription',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'manage/manage-subscription/index'},
      items: [
        'manage/manage-subscription/cloud-flex-credits-accounts',
        'manage/manage-subscription/cloud-flex-accounts',
        'manage/manage-subscription/upgrade-cloud-flex-credits-account',
        'manage/manage-subscription/upgrade-your-cloud-flex-account',
        'manage/manage-subscription/manage-billing-information',
        'manage/manage-subscription/create-manage-orgs',
        'manage/manage-subscription/create-manage-orgs-service-providers',
        'manage/manage-subscription/manage-org-settings',
        'manage/manage-subscription/account-locked',
        'manage/manage-subscription/beta-opt-in',
        'manage/manage-subscription/close-cancel-sumo-account',
      ]
    },
    {
      type: 'category',
      label: 'Partitions and Data Tiers',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'manage/partitions-and-data-tiers/index'},
      items: [
        'manage/partitions-and-data-tiers/about-partitions',
        'manage/partitions-and-data-tiers/add-partition',
        'manage/partitions-and-data-tiers/edit-partition',
        'manage/partitions-and-data-tiers/run-search-against-partition',
        'manage/partitions-and-data-tiers/view-partition-details',
        'manage/partitions-and-data-tiers/edit-data-forwarding-destinations-partition',
        'manage/partitions-and-data-tiers/manage-indexes-variable-retention',
        'manage/partitions-and-data-tiers/decommission-partition',
        'manage/partitions-and-data-tiers/data-tiers',
        'manage/partitions-and-data-tiers/data-tiers-faqs',
        'manage/partitions-and-data-tiers/searching-data-tiers',
      ]
    },
    {
      type: 'category',
      label: 'Scheduled Views',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'manage/scheduled-views/index'},
      items: [
        'manage/scheduled-views/add-scheduled-view',
        'manage/scheduled-views/pause-disable-scheduled-views',
        'manage/scheduled-views/run-search-against-scheduled-view',
        'manage/scheduled-views/scheduled-view-lag-time',
        'manage/scheduled-views/scheduled-views-best-practices',
        'manage/scheduled-views/view-list-scheduled-views',
      ]
    },
    {
      type: 'category',
      label: 'Security',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'manage/security/index'},
      items: [
        'manage/security/about-two-step-verification',
        'manage/security/two-step-for-admins',
        'manage/security/two-step-for-users',
        'manage/security/access-keys',
        'manage/security/audit-index',
        'manage/security/audit-event-index',
        'manage/security/create-allowlist-ip-cidr-addresses',
        'manage/security/data-access-level-shared-dashboards',
        'manage/security/enable-support-account',
        'manage/security/installation-tokens',
        {
          type: 'category',
          label: 'SAML',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'manage/security/saml/index'},
          items: [
            'manage/security/saml/set-up-saml',
            'manage/security/saml/integrate-with-bitium',
            'manage/security/saml/integrate-google-iam-service',
            'manage/security/saml/integrate-with-okta',
            'manage/security/saml/integrate-onelogin',
            'manage/security/saml/integrate-aws-sso',
            'manage/security/saml/integrate-azure-ad',
            'manage/security/saml/manage-permissions-with-adfs',
            'manage/security/saml/set-up-adfs-authenticate-users',
            'manage/security/saml/view-saml-debug-information',
          ]
        },
        'manage/security/search-audit-index',
        'manage/security/log-search-audit-index',
        'manage/security/set-password-policy',
        'manage/security/set-limit-user-concurrent-sessions',
        'manage/security/set-max-web-session-timeout',
      ]
    },
    {
      type: 'category',
      label: 'Users and Roles',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'manage/users-and-roles/index'},
      items: [
        {
          type: 'category',
          label: 'Manage Roles',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'manage/users-and-roles/roles/index'},
          items: [
            'manage/users-and-roles/roles/role-based-access-control',
            'manage/users-and-roles/roles/create-manage-roles',
            'manage/users-and-roles/roles/role-capabilities',
            'manage/users-and-roles/roles/construct-search-filter-for-role',
            'manage/users-and-roles/roles/add-remove-users-role',
          ]
        },
        {
          type: 'category',
          label: 'Manage Users',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'manage/users-and-roles/users/index'},
          items: [
            'manage/users-and-roles/users/create-edit-users',
            'manage/users-and-roles/users/change-users-email-address',
            'manage/users-and-roles/users/reset-user-password',
            'manage/users-and-roles/users/unlock-user-account',
            'manage/users-and-roles/users/deactivate-activate-user',
            'manage/users-and-roles/users/delete-user',
            'manage/users-and-roles/users/offboard-user',
            'manage/users-and-roles/users/multi-account-access',
            'manage/users-and-roles/users/secure-third-party-service-access',
          ]
        },
        
      ]
    },
    'manage/health-events',
    'manage/fields',
  ],
// *** DASHBOARDS and VISUALS: 
  dashboards: [
    {
      type: 'category',
      label: 'Dashboards (New)',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'dashboards-new/about-dashboard-new'},
      items: [
        'dashboards-new/create-a-dashboard-new',
        'dashboards-new/dashboard-new-faqs',
        'dashboards-new/drill-down-to-discover-root-causes',
        'dashboards-new/export-dashboard-new',
        'dashboards-new/filter-template-variables',
        'dashboards-new/link-dashboard-to-explore', 
        'dashboards-new/link-dashboard-new',
        'dashboards-new/locate-deviations-time-series',
        {
          type: 'category',
          label: 'Panels',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'dashboards-new/panels'},
          items: [
            'dashboards-new/panels/modify-chart',
            'dashboards-new/panels/area-charts',
            'dashboards-new/panels/bar-charts',
            'dashboards-new/panels/box-plot-charts',
            'dashboards-new/panels/bubble-charts',
            'dashboards-new/panels/column-charts',
            'dashboards-new/panels/combo-charts',
            'dashboards-new/panels/line-charts',
            'dashboards-new/panels/map-charts',
            'dashboards-new/panels/markdown-syntax',
            'dashboards-new/panels/pie-charts',
            'dashboards-new/panels/scatter-charts',
            'dashboards-new/panels/single-value-charts',
            'dashboards-new/panels/table-charts',
          ],
        },
        'dashboards-new/set-custom-time-ranges',
        'dashboards-new/share-a-dashboard-new',
      ],
    },
    {
      type: 'category',
      label: 'Dashboards',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'dashboards/index'},
      items: [
        'dashboards/about-dashboards',
        {
          type: 'category',
          label: 'Get Started',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'dashboards/get-started/index'},
          items: [
            'dashboards/get-started/create-dashboard',
            'dashboards/get-started/add-dashboard-link',
            'dashboards/get-started/add-links-text-panels',
            'dashboards/get-started/add-text-panel',
            'dashboards/get-started/dashboard-optimization',
            'dashboards/get-started/delete-dashboard',
            'dashboards/get-started/launch-search-data-panel',
            'dashboards/get-started/markdown-syntax',
            'dashboards/get-started/move-panel-dashboard',
            'dashboards/get-started/pause-panel',
            'dashboards/get-started/resize-panel',
            'dashboards/get-started/set-data-access-level-dashboard',
            'dashboards/get-started/title-panels',
            'dashboards/get-started/zoom-panel',
          ],
        },
        {
          type: 'category',
          label: 'Chart Panels Types',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'dashboards/chart-panel-types/index'},
          items: [
            'dashboards/chart-panel-types/area-charts',
            'dashboards/chart-panel-types/bar-charts',
            'dashboards/chart-panel-types/boolean-single-value-charts',
            'dashboards/chart-panel-types/box-plot-charts',
            'dashboards/chart-panel-types/column-charts',
            'dashboards/chart-panel-types/combo-charts',
            'dashboards/chart-panel-types/donut-pie-charts',
            'dashboards/chart-panel-types/line-charts',
            'dashboards/chart-panel-types/map-charts',
            'dashboards/chart-panel-types/numerical-single-value-charts',
            'dashboards/chart-panel-types/string-single-value-charts',
            'dashboards/chart-panel-types/table-charts',
          ],
        },
        {
          type: 'category',
          label: 'Edit Dashboards and Panels',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'dashboards/edit-dashboards/index'},
          items: [
            'dashboards/edit-dashboards/manage-dashboards',
            'dashboards/edit-dashboards/manage-charts',
            'dashboards/edit-dashboards/manage-panels',
            'dashboards/edit-dashboards/manage-axis',
            'dashboards/edit-dashboards/set-time-range-dashboards',
            'dashboards/edit-dashboards/use-filters-dashboards',
          ],
        },
        'dashboards/share-dashboard-inside-org',
        'dashboards/share-dashboard-outside-org',
        'dashboards/restricted-operators-dashboards',
      ],
    },
    {
      type: 'category',
      label: 'Alerts',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'alerts/index'},
      items: [
        'alerts/alert-variables',
        {
          type: 'category',
          label: 'Monitors',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'alerts/monitors/index'},
          items: [
            'alerts/monitors/monitor-faq',
            'alerts/monitors/terminology',
            'alerts/monitors/alert-response',
            'alerts/monitors/alert-response-faq',
            'alerts/monitors/difference-from-scheduled-searches',
            'alerts/monitors/template-variables',
          ],
        },
        {
          type: 'category',
          label: 'Scheduled Searches',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'alerts/scheduled-searches/index'},
          items: [
            'alerts/scheduled-searches/create-email-alert',
            'alerts/scheduled-searches/create-real-time-alert',
            'alerts/scheduled-searches/edit-cancel-scheduled-search',
            'alerts/scheduled-searches/generate-cse-signals-scheduled-search',
            'alerts/scheduled-searches/receive-email-alerts-scheduled-searches',
            'alerts/scheduled-searches/run-search-from-alert-email',
            'alerts/scheduled-searches/save-to-index',
            'alerts/scheduled-searches/save-to-lookup',
            'alerts/scheduled-searches/schedule-search',
            {
              type: 'category',
              label: 'FAQs',
              collapsible: true,
              collapsed: true,
              link: {type: 'doc', id: 'alerts/scheduled-searches/faqs/index'},
              items: [
                'alerts/scheduled-searches/faqs/alerts-from-static-ip-address',
                'alerts/scheduled-searches/faqs/email-alert-data-usage-exceeded',
                'alerts/scheduled-searches/faqs/failed-scheduled-search',
                'alerts/scheduled-searches/faqs/prevent-scheduled-search-timing-out',
                'alerts/scheduled-searches/faqs/real-time-alert-with-greater-than-results',
                'alerts/scheduled-searches/faqs/service-alerts-scheduled-search-email-quota-reached',
                'alerts/scheduled-searches/faqs/suspended-scheduled-search',
              ],
            },
          ],
        },
      ],
    },
  ],
// *** SEARCHES & LOGS: all search functionality
  searchlogs: [
    'search/index',
    {
      type: 'category',
      label: 'Get Started with Searches',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'search/get-started-with-search/index'},
      items: [
        {
          type: 'category',
          label: 'Search Basics',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'search/get-started-with-search/search-basics/index'},
          items: [
            'search/get-started-with-search/search-basics/about-search-basics',
            'search/get-started-with-search/search-basics/built-in-metadata',
            'search/get-started-with-search/search-basics/chart-search-results',
            'search/get-started-with-search/search-basics/comments-search-queries',
            'search/get-started-with-search/search-basics/pause-cancel-search',
            'search/get-started-with-search/search-basics/quick-search-collectors-sources',
            'search/get-started-with-search/search-basics/reference-field-special-characters',
            'search/get-started-with-search/search-basics/save-search',
            'search/get-started-with-search/search-basics/search-autocomplete',
            'search/get-started-with-search/search-basics/search-large-messages',
            'search/get-started-with-search/search-basics/search-surrounding-messages',
            'search/get-started-with-search/search-basics/share-link-to-search',
            'search/get-started-with-search/search-basics/time-range-expressions',
            'search/get-started-with-search/search-basics/view-search-results-json-logs',
            'search/get-started-with-search/search-basics/view-traces-search-results',
          ],
        },
        {
          type: 'category',
          label: 'How to Use the Search Page',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'search/get-started-with-search/search-page/index'},
          items: [
            'search/get-started-with-search/search-page/add-saved-search-favorites',
            'search/get-started-with-search/search-page/change-time-range-in-histogram',
            {
              type: 'category',
              label: 'Field Browser',
              collapsible: true,
              collapsed: true,
              link: {type: 'doc', id: 'search/get-started-with-search/search-page/field-browser/index'},
              items: [
                'search/get-started-with-search/search-page/field-browser/search-from-field-browser',
                'search/get-started-with-search/search-page/field-browser/show-hide-fields-in-field-browser',
              ],
            },
            'search/get-started-with-search/search-page/modify-search-from-messages-tab',
            'search/get-started-with-search/search-page/navigate-through-search-results',
            'search/get-started-with-search/search-page/search-highlighting',
            'search/get-started-with-search/search-page/search-load-indicator',
            'search/get-started-with-search/search-page/search-modes',
            'search/get-started-with-search/search-page/set-messages-tab-preferences',
            'search/get-started-with-search/search-page/wildcards-in-full-text-searches',
          ],
        },
        {
          type: 'category',
          label: 'Build Searches',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'search/get-started-with-search/build-search/index'},
          items: [
            'search/get-started-with-search/build-search/best-practices-search',
            'search/get-started-with-search/build-search/dynamic-parsing',
            'search/get-started-with-search/build-search/keyword-search-expressions',
            'search/get-started-with-search/build-search/search-syntax-overview',
            'search/get-started-with-search/build-search/search-templates',
            'search/get-started-with-search/build-search/set-time-range',
            'search/get-started-with-search/build-search/use-receipt-time',
            'search/get-started-with-search/build-search/use-url-to-run-search',
          ],
        },
        {
          type: 'category',
          label: 'Suggested Searches',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'search/get-started-with-search/suggested-searches/index'},
          items: [
            'search/get-started-with-search/suggested-searches/suggested-searches-apache-access-parser',
            'search/get-started-with-search/suggested-searches/suggested-searches-apache-errors-parser',
            'search/get-started-with-search/suggested-searches/suggested-searches-cisco-asa-parser',
            'search/get-started-with-search/suggested-searches/suggested-searches-microsoft-iis-parser',
            'search/get-started-with-search/suggested-searches/suggested-searches-windows-events',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Behavior Insights',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'search/behavior-insights/index'},
      items: [
        'search/behavior-insights/logexplain',
        'search/behavior-insights/logreduce-keys',
        'search/behavior-insights/logreduce-values',
      ],
    },
    {
      type: 'category',
      label: 'Live Tail',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'search/live-tail/index'},
      items: [
        'search/live-tail/about-live-tail',
        'search/live-tail/filter-live-tail',
        'search/live-tail/live-tail-cli',
        'search/live-tail/live-tail-highlighting',
        'search/live-tail/live-tail-preferences',
        'search/live-tail/live-tail-show-in-search',
        'search/live-tail/multiple-live-tails',
      ],
    },
    'search/logcompare',
    {
      type: 'category',
      label: 'LogReduce',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'search/logreduce/index'},
      items: [
        'search/logreduce/logreduce-operator',
        'search/logreduce/detect-patterns-with-logreduce',
        'search/logreduce/influence-the-logreduce-outcome',
        'search/logreduce/understand-the-logreduce-relevance-column',
      ],
    },
    'search/time-compare',
    {
      type: 'category',
      label: 'Lookup Tables',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'search/lookup-tables/index'},
      items: [
        'search/lookup-tables/create-a-lookup-table',
        'search/lookup-tables/manage-and-update-lookup-tables',
      ],
    },
    'search/optimize-search-performance',
    'search/optimizing-search-with-partitions',
    'search/subqueries',
    {
      type: 'category',
      label: 'Search Cheat Sheets',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'search/search-cheat-sheets/index'},
      items: [
        'search/search-cheat-sheets/general-search-examples-cheatsheet',
        'search/search-cheat-sheets/grep-searching-with-sumo-cheatsheet',
        'search/search-cheat-sheets/iis-search-examples-cheatsheet',
        'search/search-cheat-sheets/log-operators-cheat-sheet',
      ],
    },
    {
      type: 'category',
      label: 'Search Query Language',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'search/search-query-language/index'},
      items: [
        {
          type: 'category',
          label: 'Parse Operators',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'search/search-query-language/parse-operators/index'},
          items: [
            'search/search-query-language/parse-operators/parse-predictable-patterns-using-an-anchor',
            'search/search-query-language/parse-operators/parse-variable-patterns-using-regex',
            'search/search-query-language/parse-operators/parse-json-formatted-logs',
            'search/search-query-language/parse-operators/parse-keyvalue-formatted-logs',
            'search/search-query-language/parse-operators/parse-csv-formatted-logs',
            'search/search-query-language/parse-operators/parse-delimited-logs-using-split',
            'search/search-query-language/parse-operators/parse-xml-formatted-logs',
            'search/search-query-language/parse-operators/parse-field-option',
            'search/search-query-language/parse-operators/parse-nodrop-option',
            'search/search-query-language/parse-operators/parse-date',
            'search/search-query-language/parse-operators/parse-hex',
          ],
        },
        {
          type: 'category',
          label: 'Group or Aggregate Operators',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'search/search-query-language/group-aggregate-operators/index'},
          items: [
            'search/search-query-language/group-aggregate-operators/avg',
            'search/search-query-language/group-aggregate-operators/count-count-distinct-and-count-frequent',
            'search/search-query-language/group-aggregate-operators/first-and-last',
            'search/search-query-language/group-aggregate-operators/median',
            'search/search-query-language/group-aggregate-operators/min-and-max',
            'search/search-query-language/group-aggregate-operators/most-recent-and-least-recent',
            'search/search-query-language/group-aggregate-operators/percentile-pct',
            'search/search-query-language/group-aggregate-operators/pct-sampling',
            'search/search-query-language/group-aggregate-operators/standard-deviation',
            'search/search-query-language/group-aggregate-operators/sum',
            'search/search-query-language/group-aggregate-operators/values',
          ],
        },
        'search/search-query-language/field-expressions',
        {
          type: 'category',
          label: 'Math Expressions',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'search/search-query-language/math-expressions/index'},
          items: [
            'search/search-query-language/math-expressions/abs',
            'search/search-query-language/math-expressions/acos',
            'search/search-query-language/math-expressions/asin',
            'search/search-query-language/math-expressions/atan',
            'search/search-query-language/math-expressions/atan2',
            'search/search-query-language/math-expressions/cbrt',
            'search/search-query-language/math-expressions/ceil',
            'search/search-query-language/math-expressions/cos',
            'search/search-query-language/math-expressions/cosh',
            'search/search-query-language/math-expressions/exp',
            'search/search-query-language/math-expressions/expm1',
            'search/search-query-language/math-expressions/floor',
            'search/search-query-language/math-expressions/hypot',
            'search/search-query-language/math-expressions/isnan-and-isinfinity',
            'search/search-query-language/math-expressions/log',
            'search/search-query-language/math-expressions/log10',
            'search/search-query-language/math-expressions/log1p',
            'search/search-query-language/math-expressions/round',
            'search/search-query-language/math-expressions/sin',
            'search/search-query-language/math-expressions/sinh',
            'search/search-query-language/math-expressions/sqrt',
            'search/search-query-language/math-expressions/tan',
            'search/search-query-language/math-expressions/tanh',
            'search/search-query-language/math-expressions/todegrees',
            'search/search-query-language/math-expressions/toradians',
          ],
        },
        {
          type: 'category',
          label: 'Search Operators',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'search/search-query-language/search-operators/index'},
          items: [
            'search/search-query-language/search-operators/accum',
            'search/search-query-language/search-operators/as-operator',
            'search/search-query-language/search-operators/asn-lookup',
            'search/search-query-language/search-operators/backshift',
            'search/search-query-language/search-operators/basedecode',
            'search/search-query-language/search-operators/baseencode',
            'search/search-query-language/search-operators/bin',
            'search/search-query-language/search-operators/cat',
            'search/search-query-language/search-operators/cidr',
            'search/search-query-language/search-operators/compare',
            'search/search-query-language/search-operators/concat',
            'search/search-query-language/search-operators/contains',
            'search/search-query-language/search-operators/dectohex',
            'search/search-query-language/search-operators/dedup',
            'search/search-query-language/search-operators/diff',
            'search/search-query-language/search-operators/fields-operator',
            'search/search-query-language/search-operators/fillmissing',
            'search/search-query-language/search-operators/filter-operator',
            'search/search-query-language/search-operators/format',
            'search/search-query-language/search-operators/formatdate',
            'search/search-query-language/search-operators/geo-lookup',
            'search/search-query-language/search-operators/geoip',
            'search/search-query-language/search-operators/hash',
            'search/search-query-language/search-operators/haversine',
            'search/search-query-language/search-operators/hextoascii',
            'search/search-query-language/search-operators/hextodec',
            'search/search-query-language/search-operators/if-operator',
            'search/search-query-language/search-operators/in-operator',
            'search/search-query-language/search-operators/ipv4tonumber',
            'search/search-query-language/search-operators/isnull-isempty-isblank',
            'search/search-query-language/search-operators/isnumeric',
            'search/search-query-language/search-operators/isprivateip',
            'search/search-query-language/search-operators/ispublicip',
            'search/search-query-language/search-operators/isreservedip',
            'search/search-query-language/search-operators/isvalidip',
            'search/search-query-language/search-operators/join',
            'search/search-query-language/search-operators/length',
            'search/search-query-language/search-operators/limit',
            'search/search-query-language/search-operators/lookup',
            'search/search-query-language/search-operators/lookup-classic',
            'search/search-query-language/search-operators/lookupcontains',
            'search/search-query-language/search-operators/luhn',
            'search/search-query-language/search-operators/manually-casting-string-data-to-a-number',
            'search/search-query-language/search-operators/matches',
            'search/search-query-language/search-operators/now',
            'search/search-query-language/search-operators/num',
            'search/search-query-language/search-operators/outlier',
            'search/search-query-language/search-operators/predict',
            'search/search-query-language/search-operators/queryendtime',
            'search/search-query-language/search-operators/querystarttime',
            'search/search-query-language/search-operators/querytimerange',
            'search/search-query-language/search-operators/replace',
            'search/search-query-language/search-operators/rollingstd',
            'search/search-query-language/search-operators/save',
            'search/search-query-language/search-operators/save-lookups-classic',
            'search/search-query-language/search-operators/sessionize',
            'search/search-query-language/search-operators/smooth',
            'search/search-query-language/search-operators/sort',
            'search/search-query-language/search-operators/substring',
            'search/search-query-language/search-operators/threatip',
            'search/search-query-language/search-operators/timeslice',
            'search/search-query-language/search-operators/timeslice-join-results',
            'search/search-query-language/search-operators/tolowercase-and-touppercase',
            'search/search-query-language/search-operators/top',
            'search/search-query-language/search-operators/topk',
            'search/search-query-language/search-operators/total',
            'search/search-query-language/search-operators/tourl',
            'search/search-query-language/search-operators/trace',
            'search/search-query-language/search-operators/transpose',
            'search/search-query-language/search-operators/trim',
            'search/search-query-language/search-operators/urldecode',
            'search/search-query-language/search-operators/urlencode',
          ],
        },
        {
          type: 'category',
          label: 'Transaction Analytics',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc', 
            id: 'search/search-query-language/transaction-analytics/index',
          },
          items: [
            'search/search-query-language/transaction-analytics/merge-operator',
            'search/search-query-language/transaction-analytics/transaction-operator',
            'search/search-query-language/transaction-analytics/flow-diagrams',
            'search/search-query-language/transaction-analytics/transactionize-operator',
            ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Search FAQs',
      collapsible: true,
      collapsed: true,
      items: [
        'search/search-faqs/export-results-of-saved-file',
        'search/search-faqs/group-messages-based-on-field',
        'search/search-faqs/searching-by-keyword-returns-no-results',
      ],
    },
  ],
// *** METRICS & LOGS: all metrics content
  metricslogs: [
    'metrics/metrics',
    {
      type: 'category',
      label: 'Introduction to Metrics',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'metrics/introduction-metrics/index'},
      items: [
        'metrics/introduction-metrics/overview-sumo-metrics',
        'metrics/introduction-metrics/get-started-metrics',
        'metrics/introduction-metrics/metric-formats',
        'metrics/introduction-metrics/metric-quantization',
      ],
    },
    {
      type: 'category',
      label: 'Metric Queries and Alerts',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'metrics/metric-queries-alerts/index'},
      items: [
        'metrics/metric-queries-alerts/metrics-explorer',
        'metrics/metric-queries-alerts/metric-query-autocomplete',
        'metrics/metric-queries-alerts/metrics-explorer-faqs',
        {
          type: 'category',
          label: 'Metrics Operators',
          collapsible: true,
          collapsed: false,
          link: {type: 'doc', id: 'metrics/metric-queries-alerts/metrics-operators/index'},
          items: [
            'metrics/metric-queries-alerts/metrics-operators/accum',
            'metrics/metric-queries-alerts/metrics-operators/along',
            'metrics/metric-queries-alerts/metrics-operators/avg',
            'metrics/metric-queries-alerts/metrics-operators/bottomk',
            'metrics/metric-queries-alerts/metrics-operators/count',
            'metrics/metric-queries-alerts/metrics-operators/delta',
            'metrics/metric-queries-alerts/metrics-operators/eval',
            'metrics/metric-queries-alerts/metrics-operators/fillmissing',
            'metrics/metric-queries-alerts/metrics-operators/filter',
            'metrics/metric-queries-alerts/metrics-operators/histogram-quantile',
            'metrics/metric-queries-alerts/metrics-operators/max',
            'metrics/metric-queries-alerts/metrics-operators/min',
            'metrics/metric-queries-alerts/metrics-operators/outlier',
            'metrics/metric-queries-alerts/metrics-operators/parse',
            'metrics/metric-queries-alerts/metrics-operators/pct',
            'metrics/metric-queries-alerts/metrics-operators/quantize',
            'metrics/metric-queries-alerts/metrics-operators/rate',
            'metrics/metric-queries-alerts/metrics-operators/sum',
            'metrics/metric-queries-alerts/metrics-operators/topk',
          ],
        },
        'metrics/metric-queries-alerts/metric-query-error-messages',
        'metrics/metric-queries-alerts/share-metric-query',
        'metrics/metric-queries-alerts/metrics-queries-classic',
      ],
    },
    {
      type: 'category',
      label: 'Metric Charts',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'metrics/metric-charts/index'},
      items: [
        'metrics/metric-charts/create-metrics-visualization',
        'metrics/metric-charts/line-area-metric-charts',
        'metrics/metric-charts/single-value-metric-charts',
        'metrics/metric-charts/interacting-metric-charts',
        'metrics/metric-charts/quantization-interval-chart',
        'metrics/metric-charts/metrics-outliers',
        'metrics/metric-charts/add-metrics-visualization-to-dashboard',
        'metrics/metric-charts/log-overlay-analyze-metrics-visualizations',
      ],
    },
    {
      type: 'category',
      label: 'Understand and Manage Metric Volume',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'metrics/understand-manage-metric-volume/index'},
      items: [
        'metrics/understand-manage-metric-volume/data-limits-for-metrics',
        'metrics/understand-manage-metric-volume/disabled-metrics-sources',
        'metrics/understand-manage-metric-volume/metric-ingestion-and-storage',
        'metrics/understand-manage-metric-volume/metric-throttling',
      ],
    },
    {
      type: 'category',
      label: 'Metric Rules Editor',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'metrics/metric-rules-editor/index'},
      items: [
        'metrics/metric-rules-editor/about-metric-rules',
        'metrics/metric-rules-editor/create-metric-rules',
      ],
    },
    'metrics/metrics-transformation-rules',
    'metrics/kubernetes-metrics',
    'metrics/logs-to-metrics',
  ],
// *** INTEGRATIONS: Sumo Logic Apps, no longer called APPS
  integrations: [
    'integrations/integrations',
    {
      type: 'category',
      label: 'PCI Compliance',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'integrations/pci-compliance/pci-compliance'},
      items: [
        'integrations/pci-compliance/setup-sumologic-pci-app',
        'integrations/pci-compliance/pci-reports',
        'integrations/pci-compliance/pci-dashboards',
      ],
    },
  ],
// OTHER FEATURES: Global Intelligence, SDO, CSE
  other: [
    {
      type: 'category',
      label: 'Global Intelligence',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'global-intelligence/index'},
      items: [
        {
          type: 'category',
          label: 'Apache',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'global-intelligence/apache/index'},
          items: [
            'global-intelligence/apache/install-for-apache-view-dashboards',
            'global-intelligence/apache/collect-logs-apache',
          ],
        },
        {
          type: 'category',
          label: 'Apache Tomcat',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'global-intelligence/apache/index'},
          items: [
            'global-intelligence/apache-tomcat-app/install-for-apache-tomcat-view-dashboards',
            'global-intelligence/apache-tomcat-app/collect-logs-tomcat-app',
          ],
        },
        {
          type: 'category',
          label: 'Nginx',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'global-intelligence/nginx/index'},
          items: [
            'global-intelligence/nginx/install-for-nginx-view-dashboards',
            'global-intelligence/nginx/collect-logs-nginx',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'SDO',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'sdo/index'},
      items: [
        'sdo/about-sdo',
        'sdo/supported-tools-schema',
        {
          type: 'category',
          label: 'Set Up SDO Solution',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'sdo/set-up-sdo/index'},
          items: [
            'sdo/set-up-sdo/sdo-manual-configuration',
            'sdo/set-up-sdo/sdo-setup-from-atlassian-marketplace',
            'sdo/set-up-sdo/sdo-setup-with-terraform-script',
          ],
        },
        `sdo/install-sdo-app-view-dashboards`,
        'sdo/view-sdo-dashboards',
        'sdo/integrate-tools-with-sdo',
        'sdo/jenkins-plugin-build-deploy-events',
      ],
    },
    {
      type: 'category',
      label: 'Cloud SIEM Enterprise',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'cloud-siem/index.md'},
      items: [
        {
          type: 'category',
          label: 'Administration',
          collapsible: true,
          collapsed: false,
          link: {type: 'doc', id: 'cloud-siem/administration/index.md'},
          items: [
            'cloud-siem/administration',
          ],
        },
      ],
    },
  ],
  //Contribution guide for documentation
  contribution: [
    {
      type: 'category',
      label: 'Contribution Guide',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'contribution/index'},
      items: [
        'contribution/create-document',
        'contribution/markdown-features',
        'contribution/release-notes',
        'contribution/build-deploy',
        'contribution/translate',
        {
          type: 'category',
          label: 'Templates',
          collapsible: true,
          collapsed: false,
          items: [
            'contribution/templates/partner-app',
            'contribution/templates/template-doc'
          ]
        }
      ],
    },
  ],
}
