# Use Fluent Bit base image
FROM index.docker.io/fluent/fluent-bit:latest

# Set the working directory
WORKDIR /root

# Copy the output_conf.yaml file into the container's root directory
COPY ./output_conf.yaml output_conf.yaml