name: Build and Deploy

on:
  workflow_call:
    inputs:
      hostname:
        description: Host name of the deployed environment
        required: true
        type: string
    secrets:
      S3_BUCKET_NAME:
        required: true
      CLOUDFRONT_DISTRIBUTION_ID:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    env:
      CI: true
      NODE_ENV: production
      AWS_PAGER: ""
      HOSTNAME: ${{ inputs.hostname }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_EC2_METADATA_DISABLED: "true"
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          cache: 'yarn'
      - name: Install awscli
        uses: unfor19/install-aws-cli-action@v1
      - name: Install jq
        run: sudo apt-get install jq
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build the Docusaurus site
        run: yarn build
      - name: Deploy the Docusaurus site to staging
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws s3 sync --delete build/ s3://${S3_BUCKET_NAME}/
          export INVALIDATION_ID=$(
            aws cloudfront create-invalidation \
              --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
              --paths "/*" \
            | jq -r .Invalidation.Id
          )
          aws cloudfront wait invalidation-completed \
            --id $INVALIDATION_ID \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID
