name: deploy-to-staging

on:
  push:
    branches:
      - main

jobs:
  deploy-to-staging:
    uses: SumoLogic/sumologic-documentation/.github/workflows/build_and_deploy.yml@main
    with:
      s3_bucket_name: ${{ secrets.STAGING_S3_BUCKET_NAME }}
      cloudfront_distribution_id: ${{ secrets.STAGING_CLOUDFRONT_DISTRIBUTION_ID }}
      hostname: d10g313yy2pc88.cloudfront.net
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
