name: deploy-to-staging

on:
  push:
    branches:
      - main

jobs:
  deploy-to-staging:
    runs-on: ubuntu-20.04
    env:
      CI: true
      NODE_ENV: production
      AWS_PAGER: ""
      STAGING_HOSTNAME: d10g313yy2pc88.cloudfront.net
      AWS_DEFAULT_REGION: us-east-1
      AWS_EC2_METADATA_DISABLED: "true"
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          cache: 'yarn'
      - name: Install awscli
        uses: unfor19/install-aws-cli-action@v1
      - name: Install jq
        run: sudo apt-get install jq
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build the Docusaurus site
        run: yarn build
      - name: Deploy the Docusaurus site to staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.STAGING_S3_BUCKET_NAME }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.STAGING_CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws s3 sync --delete build/ s3://${S3_BUCKET_NAME}/
          export INVALIDATION_ID=$(
            aws cloudfront create-invalidation \
              --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
              --paths "/*" \
            | jq -r .Invalidation.Id
          )
          aws cloudfront wait invalidation-completed \
            --id $INVALIDATION_ID \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID
