name: deploy-to-review

on:
  push:
    branches:
# To enable staging, replace 'test' with your branch name
      - test

jobs:
  deploy-to-review:
    uses: SumoLogic/sumologic-documentation/.github/workflows/build_and_deploy.yml@main
    with:
      hostname: https://d10g313yy2pc88.cloudfront.net
      base_url: /${{ github.ref_name }}/
      environment: review/${{ github.ref_name }}
    secrets:
      S3_BUCKET_NAME: ${{ secrets.REVIEW_S3_BUCKET_NAME }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.REVIEW_CLOUDFRONT_DISTRIBUTION_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
